import type { Metadata } from 'next'
import MangaList from "@/components/manga-list";

export const metadata: Metadata = {
  title: 'Manga Search',
  description: 'Generated by create next app',
}

export default async function MangaPage() {
  
  const response = await fetch('https://manga-apiv1.vercel.app/api/popular',  {
    method: 'GET',
    redirect: 'follow'
  });

  const data = await response.json();

  return (
    <main className="text-center pt-12 pb-12 px-5 flex-1">
      <h1 className="text-4xl md:text-5xl
      font-bold mb-5">
        Popular Manga
      </h1>
        <MangaList data={data} />
    </main>
  )
}